import { v4 as uuid } from "uuid";
/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [
  // comebacks
  {
    _id: uuid(),
    title: "Most EMOTIONAL Comebacks of the Season - 2021/22",
    category: "Comebacks",
    creator: "Vanemas",
    views: "1,665,717",
    date: "Oct 29, 2021",
    likes: "30K",
    thumbnail: "/assets/thumbnail/comeback1.jpeg",
    url: "https://www.youtube.com/embed/fY3ZwG8u9ZE",
    sub: "1.2M",
    description:
      "There have been so many comebacks already this season. Cristiano Ronaldo is often on the winning side of them.",
  },
  {
    _id: uuid(),
    title: "10 MOST EMOTIONAL COMEBACKS IN FOOTBALL • BEST COMEBACKS IN FOOTBALL HISTORY",
    category: "Comebacks",
    creator: "FELO",
    views: "950,711",
    date: "Apr 22, 2020",
    likes: "8.6K",
    thumbnail: "/assets/thumbnail/comeback2.jpeg",
    url: "https://www.youtube.com/embed/wzZn0BEw9cI",
    sub: "1.2M",
    description:
      "This video contains the Most Emotional and Most Legendary Comebacks in Football History such as Milan vs Liverpool, Real Madrid vs Atletico, Barcelona vs PSG and many others.",
  },
  {
    _id: uuid(),
    title: "Most Dramatic Football Matches 2020 Crazy Comebacks",
    category: "Comebacks",
    creator: "Sir Alex",
    views: "11,538,797",
    date: "Mar 17, 2020",
    likes: "218K",
    thumbnail: "/assets/thumbnail/comeback3.jpeg",
    url: "https://www.youtube.com/embed/hM3XUuY1MN8",
    sub: "1.2M",
    description:
      "There were few thrilling and dramatic football matches in this 2019-2020 season. Great comebacks and tense moments, epic and legendary last minute goals 2020. Great matche was between Liverpool vs Atletico Madrid on Champions League. Diego Simeone's crazy reactions were priceless after Llorente and Morata goals. Wolves made a several unbelievable comebacks vs Manchester City and Tottenham in Premier League. Amazing tensed match between Ajax and Chelsea 4-4. Borussia Dortmund vs Inter 3-2 was one of the most dramatic match on UCL. Liverpool vs Salzburg 4-3, great play by Salzburg etc.",
  },
  {
    _id: uuid(),
    title: "Man United Best Comebacks This Season 2021/22",
    category: "Comebacks",
    creator: "SkStudioz",
    views: "931,906",
    date: "Dec 13, 2021",
    likes: "18K",
    thumbnail: "/assets/thumbnail/comeback4.jpeg",
    url: "https://www.youtube.com/embed/e1aLgTXl0hI",
    sub: "1.2M",
    description:
      "Man United Best Comebacks This Season 2021/22 (english commentary)",
  },
  // celebration
  {
    _id: uuid(),
    title: "Funny & Crazy Goal Celebrations ● Football Show ● HD",
    category: "Celebration",
    creator: "MNXHD",
    views: "1,986,018",
    date: "Jan 11, 2018",
    likes: "22K",
    thumbnail: "/assets/thumbnail/celebration1.jpeg",
    url: "https://www.youtube.com/embed/itiaHDzt9Rk",
    sub: "1.2M",
    description:
      "Football Goal Celebrations ● Funny & Crazy Goal Celebrations - Best, Crazy, Funny Football Goal Celebrations: Ronaldinho, Lingard, Pogba, Dybala, Griezmann, Lewandowski, Ronaldo etc.",
  },
  {
    _id: uuid(),
    title: "11 most iconic goal celebrations in football history | Oh My Goal",
    category: "Celebration",
    creator: "Soccer Stories - Oh My Goal",
    views: "467,201",
    date: "Feb 21, 2021",
    likes: "13K",
    thumbnail: "/assets/thumbnail/celebration2.jpeg",
    url: "https://www.youtube.com/embed/3nLQFLHW82Q",
    sub: "1.2M",
    description:
      "Goal celebrations are as much a part of football as the goals. And there are some legendary celebration in this sport! Here are 11 celebrations that have gone down in football history!",
  },
  {
    _id: uuid(),
    title: "Never Celebrate a Goal This Way",
    category: "Celebration",
    creator: "BRAIN TIME",
    views: "14,155,377",
    date: "Sep 1, 2018",
    likes: "93K",
    thumbnail: "/assets/thumbnail/celebration3.jpeg",
    url: "https://www.youtube.com/embed/GRZeiPnoZw8",
    sub: "1.2M",
    description:
      "Football causes a huge number of different emotions among people. Some people love it, other people hate it, and during the games the fans send their love to their team and find the most unusual ways to express their joy... but also other emotions. And sometimes the players also want to somehow let out their happiness after they score a goal. You might think it's okay for them to celebrate. However, players sometimes behave not according to the rules of football.",
  },
  {
    _id: uuid(),
    title: "Epic goal celebration in football | Top 10 goal celebrations",
    category: "Celebration",
    creator: "Freak edits",
    views: "69,000",
    date: "Jan 9, 2021",
    likes: "1K",
    thumbnail: "/assets/thumbnail/celebration4.jpeg",
    url: "https://www.youtube.com/embed/osARlySjRT0",
    sub: "1.2M",
    description:
      "These celebrations has taken over the world. Almost all football fans are doing this.",
  },
  // goals
  {
    _id: uuid(),
    title: "Unforgettable Goals in Football",
    category: "Goals",
    creator: "TKHD",
    views: "21,534,295",
    date: "May 4, 2020",
    likes: "191K",
    thumbnail: "/assets/thumbnail/goals1.jpeg",
    url: "https://www.youtube.com/embed/r_lN52VwrBo",
    sub: "1.2M",
    description:
      "Unforgettable, spectacular and best goals in football. Ronaldo, Messi, Neymar, Ronaldinho, Balotelli, Balle, Ibrahimovic and more in the video!",
  },
  {
    _id: uuid(),
    title: "Top 35 Legendary Goals In Football History",
    category: "Goals",
    creator: "Notelicioux",
    views: "10,414,517",
    date: "Nov 1, 2018",
    likes: "106K",
    thumbnail: "/assets/thumbnail/goals2.jpeg",
    url: "https://www.youtube.com/embed/RLxWIgoo-ic",
    sub: "1.2M",
    description:
      "Top 35 Legendary Goals In Football History ft. Ronaldinho, Pele, Diego Maradona, Johan Cruyff, Zinedine Zidane etc.",
  },
  {
    _id: uuid(),
    title: "100 Best Goals Of The Decade • 2010-2019",
    category: "Goals",
    creator: "Notelicioux",
    views: "3,679,103",
    date: "Dec 17, 2019",
    likes: "34K",
    thumbnail: "/assets/thumbnail/goals3.jpeg",
    url: "https://www.youtube.com/embed/64Vu-Vn8Hyk",
    sub: "1.2M",
    description:
      "100 Best Goals Of The Decade • 2010-2019 ft. Lionel Messi, Zlatan Ibrahimovic, Cristiano Ronaldo, Wayne Rooney, Neymar, Robin van Persie, James Rodriguez, Mohamed Salah etc.",
  },
  {
    _id: uuid(),
    title: "20 CRAZIEST Goals In Football History",
    category: "Goals",
    creator: "KickFlix",
    views: "2,947,482",
    date: "Jan 29, 2022",
    likes: "27K",
    thumbnail: "/assets/thumbnail/goals4.jpeg",
    url: "https://www.youtube.com/embed/y8H9AOf413M",
    sub: "1.2M",
    description:
    "These are the 20 CRAZIEST Goals in Football History...",
  },
  // skills
  {
    _id: uuid(),
    title: "Top 50+ Unique & Original Football Skills",
    category: "Skills",
    creator: "Home of Football",
    views: "5,965,141",
    date: "Aug 24, 2019",
    likes: "74K",
    thumbnail: "/assets/thumbnail/skills1.jpeg",
    url: "https://www.youtube.com/embed/OOvyseZM1gQ",
    sub: "1.2M",
    description: "What's the player that you have in your mind when we talk about unique and original skills? Skills that will blow your mind. Check out all skills in the video!",
  },
  {
    _id: uuid(),
    title: "Most Humiliating Skills in Football",
    category: "Skills",
    creator: "TKHD",
    views: "20,873,111",
    date: "Nov 2, 2019",
    likes: "226K",
    thumbnail: "/assets/thumbnail/skills2.jpeg",
    url: "https://www.youtube.com/embed/MuARV64u7g0",
    sub: "1.2M",
    description: "The most humiliating, amazing skills in football. Van Dijk, Salah, Ronaldo, Messi, Kaka and more in video!",
  },
  {
    _id: uuid(),
    title: "These Football Skills Should Be Illegal",
    category: "Skills",
    creator: "JN Football",
    views: "15,700,821",
    date: "May 16, 2020",
    likes: "199K",
    thumbnail: "/assets/thumbnail/skills3.jpeg",
    url: "https://www.youtube.com/embed/DQ3jAuEDVT0",
    sub: "1.2M",
    description: "Football skills that should be illegal because they totally embarrassed their defenders.",
  },
  {
    _id: uuid(),
    title: "0% Luck, 100% Skill",
    category: "Skills",
    creator: "Teo CRi",
    views: "21,128,998",
    date: "Dec 9, 2021",
    likes: "126K",
    thumbnail: "/assets/thumbnail/skills4.jpeg",
    url: "https://www.youtube.com/embed/wDaJHvAeGqo",
    sub: "1.2M",
    description: "Some of the craziest football skills done live by the best in the game.",
  },
  // Champions League
  {
    _id: uuid(),
    title: "Peter Drury's Best Champions League Matches 2021/22",
    category: "Champions League",
    creator: "SkStudioz2",
    views: "27,533",
    date: "May 6, 2022",
    likes: "1.6K",
    thumbnail: "/assets/thumbnail/ucl1.jpeg",
    url: "https://www.youtube.com/embed/eyyXmYABcxE",
    sub: "1.2M",
    description: "Peter Drury's Best Champions League Matches Commentary 2021/22",
  },
  {
    _id: uuid(),
    title: "Legendary Champions League Matches (HD)",
    category: "Champions League",
    creator: "Calcio Show",
    views: "1,677,804",
    date: "May 10, 2020",
    likes: "27K",
    thumbnail: "/assets/thumbnail/ucl2.jpeg",
    url: "https://www.youtube.com/embed/IYW3uVpx2e4",
    sub: "1.2M",
    description: "The best and most incredible matches in the UEFA Champions League",
  },
  {
    _id: uuid(),
    title: "Unforgettable Champions League Matches",
    category: "Champions League",
    creator: "NostBall",
    views: "544,703",
    date: "Feb 25, 2022",
    likes: "7K",
    thumbnail: "/assets/thumbnail/ucl3.jpeg",
    url: "https://www.youtube.com/embed/w_cnjJ7e04M",
    sub: "1.2M",
    description: "The best and most incredible matches in the UEFA Champions League - English Commentary",
  },
  {
    _id: uuid(),
    title: "BEST CL Knock Out Matches EVER",
    category: "Champions League",
    creator: "Vanemas Football",
    views: "628,711",
    date: "Nov 29, 2021",
    likes: "7.8K",
    thumbnail: "/assets/thumbnail/ucl4.jpeg",
    url: "https://www.youtube.com/embed/XFaBLMsxNcE",
    sub: "1.2M",
    description: "It's about classic games and clashes between two teams in the Champions League. In the video the matches and clashes are over 2 games. The matches, especially the second leg, were nerve wrecking, exciting and very close. Football can be amazing and this video shows some of the most amazing matches from the Champions League.",
  },
  // Premier League
  {
    _id: uuid(),
    title: "BEST Premier League Goals of the Decade | 2010 - 2019",
    category: "Premier League",
    creator: "Premier League",
    views: "13,508,902",
    date: "Dec 30, 2019",
    likes: "85K",
    thumbnail: "/assets/thumbnail/pl1.jpeg",
    url: "https://www.youtube.com/embed/4Dk7eYoj5GI",
    sub: "1.2M",
    description: "This video features Wayne Rooney’s bicycle kick v Manchester City, Papiss Cissé’s wonder strike against Chelsea, Olivier Giroud’s scorpion kick against Crystal Palace and loads more!",
  },
  {
    _id: uuid(),
    title: "Highest-scoring Premier League Matches",
    category: "Premier League",
    creator: "Premier League",
    views: "3,831,716",
    date: "May 12, 2020",
    likes: "42K",
    thumbnail: "/assets/thumbnail/pl2.jpeg",
    url: "https://www.youtube.com/embed/sZRvZaeCNNg",
    sub: "1.2M",
    description: "A compilation of the six highest-scoring matches in Premier League history. West Bromwich Albion 5-5 Manchester United. Arsenal 7-3 Newcastle United. Manchester United 8-2 Arsenal. Tottenham Hotspur 9-1 Wigan Athletic. Tottenham Hotspur 6-4 Reading. Portsmouth 7-4 Reading.",
  },
  {
    _id: uuid(),
    title: "Manchester United 3-2 Spurs | EXTENDED HIGHLIGHTS",
    category: "Premier League",
    creator: "Tottenham Hotspur",
    views: "2,840,004",
    date: "Mar 14, 2022",
    likes: "43K",
    thumbnail: "/assets/thumbnail/pl3.jpeg",
    url: "https://www.youtube.com/embed/YLUcuP4EOfA",
    sub: "1.2M",
    description: "Watch the extended highlights as a Cristiano Ronaldo hat-trick meant Tottenham Hotspur lost 3-2 to Manchester United at Old Trafford in the Premier League.",
  },
  {
    _id: uuid(),
    title: "Ronaldo stars as United beat 10-man Liverpool | Manchester United 3-0 Liverpool (2008) | Classics",
    category: "Premier League",
    creator: "Manchester United",
    views: "10,879,586",
    date: "Feb 23, 2019",
    likes: "139K",
    thumbnail: "/assets/thumbnail/pl4.jpeg",
    url: "https://www.youtube.com/embed/qsyFbyX5PuY",
    sub: "1.2M",
    description: "Relive this classic win over Liverpool as Cristiano Ronaldo bagged his first goal against our huge rivals, with Wes Brown and Nani rounding off a perfect afternoon at Old Trafford!",
  },
];
